server:
  port: 9080
# 数据库连接
spring:
  profiles:
    active: zhaoyu
#    active: p
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8 # 解决中国时间少八个小时
    locale: zh_CN
    # 解决json 返回过程中long精度丢失问题
    generator:
      write-numbers-as-strings: true
      write-bigdecimal-as-plain: true
  mvc:
    servlet:
      load-on-startup: 1 # springboot接口第一次访问都很慢 是因为不是一开始就加载的是有访问才开始加载
  main:
    allow-bean-definition-overriding: true

#Mybatis-plus 配置
mybatis-plus:
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: Classpath*:/mapper/*.xml
  type-aliases-package: com.naraci


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '用户系统服务'
      paths-to-match: '/**'
      packages-to-scan: com.naraci.app.web

    - group: '视频解析服务'
      paths-to-match: '/**'
      packages-to-scan: com.naraci.app.wechatconfig
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn



logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

