# 数据库连接
spring:
  profiles:
    active: zhaoyu
#    active: p
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8 # 解决中国时间少八个小时
    locale: zh_CN
    # 解决json 返回过程中long精度丢失问题
    generator:
      write-numbers-as-strings: true
      write-bigdecimal-as-plain: true
  mvc:
    servlet:
      load-on-startup: 1 # springboot接口第一次访问都很慢 是因为不是一开始就加载的是有访问才开始加载
  main:
    allow-bean-definition-overriding: true

#Mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.naraci.app.domain
  configuration:
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '资源爬取基础服务'
      paths-to-match: '/**'
      packages-to-scan: com.naraci.app.BaseServer

    - group: '用户系统服务'
      paths-to-match: '/**'
      packages-to-scan: com.naraci.app.web

    - group: '视频解析服务'
      paths-to-match: '/**'
      packages-to-scan: com.naraci.app.media

    - group: '管理员操作服务'
      paths-to-match: '/**'
      packages-to-scan: com.naraci.app.AdminManage
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

# jwt自定义配置
jwt:
  expireTime: 2592000000
  key: 66636naraci


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

