server:
  port: 9080
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yuziapi?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    hikari:
      maximum-pool-size: 50  # 最大连接数
      minimum-idle: 10       # 设置较低的最小空闲连接数，避免保持过多空闲连接
      connection-timeout: 30000  # 获取连接超时时间，设置为30秒
      pool-name: my-test-hikari  # 连接池名称
      idle-timeout: 300000       # 空闲超时时间，设为5分钟，略低于MySQL的默认`wait_timeout`，以便Hikari及时回收空闲连接
      auto-commit: true          # 是否自动提交
      max-lifetime: 1800000      # 最大存活时间，设为30分钟
      connection-test-query: "SELECT 1"  # 每次从池中借出连接时测试有效性
      validation-timeout: 2000          # 验证连接的超时时间，设为2秒
      keepalive-timeout: 60000          # 启用`keep-alive`查询，每隔1分钟保持连接活跃



  data:
    redis:
      port: 6379
      host: 123
      password:
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
  mail:
    host: smtpdm.aliyun.com
    port: 465
    username: 123
    password: 123
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false
